### ISSUE TITLE
backport to 1.19.2

### ISSUE THREAD

**Issue by furtabs** [Lemon-Juiced/BetterSilicon#1]
most modpacks are still on this version. should just take a recompile, no code changes

**Comment by Lemon-Juiced** [comment]
Without recoding the whole mod, this will not work. This uses the new 1.19.3 creative tab method, which does not exist in 1.19.2. If I had more free time I would consider it, but I don't have enough time right now to recode the mod (even though it is very small), and it doesn't help that 1.19.4 is slated to release today.

**Comment by Lemon-Juiced** [comment]
I will consider back porting it soon if I get free time however, it might be too late now.

**Comment by Lemon-Juiced** [comment]
It has been backported, I anticipated modders would move up to 1.19.4 once it was released, but it seems I was mislead.

**Comment by furtabs** [comment]
1.19.4 is a snapshot for 1.20 1.19.2 is the last actual 1.19 version
